### ISSUE TITLE
Can't run Learn IDE

### ISSUE THREAD

**Issue by TechnoMom** [learn-co-curriculum/welcome-to-learn-5#14]
After authenticating my account for the first time, the Learn IDE says it's loading my remote code (I don't have any that I know of), then crashes with the following message:
![learnidecrash2](https://cloud.githubusercontent.com/assets/17887141/20902075/8b2c1f8c-bb03-11e6-976a-9097183f471e.png)

I've already completely uninstalled (including removing the atom folder) and reinstalled, restarted, etc. I'm using the latest version of the application. I'm running Windows 10 Pro 64-bit. I've disabled my security software, and nothing but Google Chrome is running other than the IDE.

Thank you,
Cyn
cyn@cynthiaarmistead.com

**Comment by aturkewi** [comment]
Hi @TechnoMom sorry for the slow response here.
The best place to get answer for this type of thing is the Ask A Question button in Learn. We have Learn Experts staffing that channel from 9am to 1am (US Eastern times). They can give you immediate support :)

That being said, we've made many update to the IDE since December. If you're still interested in learning with us, you can download the latest version here: http://help.learn.co/the-learn-ide/downloading-and-using-the-ide and if you get stuck, you can use the Ask A Question in Learn to get immediate live support :)
