### ISSUE TITLE
Loop on first lesson

### ISSUE THREAD

**Issue by droidstir** [learn-co-curriculum/welcome-to-learn-5#28]
I am having the same issue as everyone else,

"I have downloaded everything and done the first steps in the IDE, the lessons are not linking up because safari is my default browser, how to I move on to the next lesson, if it wont allow me to mark that the tasks have been completed?"

**Comment by aturkewi** [comment]
@droidstir to get the Learn IDE authentication light to turn green you'll have to be using Chrome. You may also need to log into the Learn IDE with the email and password setup when you downloaded the IDE rather than your github account. 

The best way to get immediate help with this though is to use the Ask A Question button in Learn. We have Learn Experts on from 9am-1am Eastern US times to help :)
