### ISSUE TITLE
Learn IDE seems buggy

### ISSUE THREAD

**Issue by joselycas** [learn-co-curriculum/welcome-to-learn-5#32]
The Learn IDE application is duplicating the text I type into the terminal. How do I get this fixed?

**Comment by aturkewi** [comment]
Hey @joselycas this was an issue with the Learn IDE for a little bit, but we have since updated the Learn IDE to fix this :) You can download the latest version here: http://help.learn.co/the-learn-ide/downloading-and-using-the-ide

Also, this isn't really a problem with this lab specifically. The best place to ask this question to get immediate support would be the Ask A Question button in Learn. That service is staffed with Learn Experts from 9am - 1am Eastern time and they're happy to help answer questions :)
