### ISSUE TITLE
not able to start the course

### ISSUE THREAD

**Issue by shilpak** [learn-co-curriculum/welcome-to-learn-5#37]
after typing learn i get lot of messages in red.

**Comment by aturkewi** [comment]
Hey @shilpak thanks for letting us know. This may be because you still need to edit and save the file (check out the video walkthrough to see how it's done).

Also, the best way to get immediate help with this is through the Ask A Question button on Learn. We have Learn Experts online there from 9am to 1am Easter times and they're always happy to help :) They'll also be able to chat with you to get follow up information that may help solve the problem (such as the content of the error message).
